# Generated by Django 4.1.7 on 2023-02-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Expense", "Expense"),
                            ("Loan", "Loan"),
                        ],
                        default="Expense",
                        max_length=10,
                    ),
                ),
                ("purpose", models.CharField(max_length=200)),
                ("amount", models.FloatField(max_length=6)),
                ("due_date", models.DateField()),
                (
                    "repeat_pattern",
                    models.CharField(
                        choices=[
                            ("monthly", "monthly"),
                            ("weekly", "weekly"),
                            ("every two weeks", "every two weeks"),
                            ("every three weeks", "every three weeks"),
                            ("every four weeks", "every four weeks"),
                        ],
                        default="monthly",
                        max_length=30,
                    ),
                ),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.PositiveBigIntegerField()),
                ("end_date", models.DateField()),
                ("date_added", models.DateField(default="21/02/2023", editable=False)),
            ],
        ),
    ]
