# Generated by Django 4.1.7 on 2023-03-03 09:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Expense", "Expense"),
                            ("Loan", "Loan"),
                        ],
                        default="Expense",
                        max_length=25,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=200)),
                ("amount", models.FloatField(max_length=6)),
                ("due_date", models.DateField(default=datetime.date(2023, 3, 3))),
                (
                    "repeat_pattern",
                    models.CharField(
                        choices=[
                            ("one off", "one off"),
                            ("monthly", "monthly"),
                            ("weekly", "weekly"),
                            ("every two weeks", "every two weeks"),
                            ("every three weeks", "every three weeks"),
                            ("every four weeks", "every four weeks"),
                        ],
                        default="one off",
                        max_length=25,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
