# Generated by Django 4.1.7 on 2023-02-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="repeat_pattern",
            field=models.CharField(
                choices=[
                    ("one off", "one off"),
                    ("monthly", "monthly"),
                    ("weekly", "weekly"),
                    ("every two weeks", "every two weeks"),
                    ("every three weeks", "every three weeks"),
                    ("every four weeks", "every four weeks"),
                ],
                default="monthly",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="telefone",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
