# Generated by Django 4.1.7 on 2023-03-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 3, 15)),
        ),
    ]
