# Generated by Django 4.1.7 on 2023-03-07 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0002_alter_transaction_due_date_grouptransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 3, 7)),
        ),
    ]
