# Generated by Django 4.1.7 on 2023-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0003_transaction_delete_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="email",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="end_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="telefone",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="website",
            field=models.URLField(default=None, null=True),
        ),
    ]
