# Generated by Django 4.1.7 on 2023-04-26 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0003_alter_transaction_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
