# Generated by Django 4.1.7 on 2023-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0004_alter_transaction_due_date_alter_transaction_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="repeat_pattern",
            field=models.CharField(
                choices=[
                    ("one off", "one off"),
                    ("monthly", "monthly"),
                    ("weekly", "weekly"),
                    ("every two weeks", "every two weeks"),
                    ("every three weeks", "every three weeks"),
                    ("every four weeks", "every four weeks"),
                ],
                default="monthly",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="telefone",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
