# Generated by Django 4.1.7 on 2023-02-22 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0005_alter_transaction_due_date_alter_transaction_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_added",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 22, 10, 51, 19, 324681, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
