# Generated by Django 4.1.7 on 2023-02-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0009_alter_transaction_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="repeat_pattern",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
    ]
