# Generated by Django 4.1.7 on 2023-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0010_remove_transaction_repeat_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="repeat_pattern",
            field=models.CharField(
                choices=[
                    ("one off", "one off"),
                    ("monthly", "monthly"),
                    ("weekly", "weekly"),
                    ("every two weeks", "every two weeks"),
                    ("every three weeks", "every three weeks"),
                    ("every four weeks", "every four weeks"),
                ],
                default="one off",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Loan", "Loan"),
                ],
                default="Expense",
                max_length=25,
            ),
        ),
    ]
