# Generated by Django 4.1.7 on 2023-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0011_transaction_repeat_pattern_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
