# Generated by Django 4.1.7 on 2023-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0014_alter_transaction_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
