# Generated by Django 4.1.7 on 2023-02-25 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0016_alter_transaction_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 2, 25)),
        ),
    ]
