# Generated by Django 4.1.7 on 2023-02-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0018_alter_transaction_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="transaction_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 2, 28)),
        ),
    ]
