# Generated by Django 4.1.7 on 2023-03-01 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0019_rename_type_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 3, 1)),
        ),
    ]
