# Generated by Django 4.1.7 on 2023-03-07 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usergroup",
            old_name="nr_of_users",
            new_name="nr_of_members",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="user_ids",
        ),
        migrations.AddField(
            model_name="usergroup",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
