# Generated by Django 4.1.7 on 2023-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_active_group_myuser_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="as_group",
            field=models.BooleanField(default=False),
        ),
    ]
